# -*- coding: utf-8 -*-
"""calc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cIPu9Y1zvLd8t6T40doxCJsOul-CAo5u
"""



# @title

  print("Integer Calculator")
  first = input("First number?")
  op = input("Operation? + - * /")
  second = input("Second number")
  if op == "+":
    print(int(first) + int(second))
  elif op == "-":
    print(int(first) - int(second))
  elif op == "*":
   print(int(first) * int(second))
  else:
   print(int(first) / int(second))

"""."""
