# -*- coding: utf-8 -*-
"""calc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cIPu9Y1zvLd8t6T40doxCJsOul-CAo5u
"""



# @title
x = str(3)
y = int(3)
z = 1 #integer
w = 0.1 #float
a = "unique" #string
b = "4" #string
c = True #boolean
myList = [x, y, z, w, a, b, c]
  print("Integer Calculator by Amber Lam")
  first = input("First number?")
  op = input("Operation? + - * /")
  second = input("Second number")
  if op == "+":
    print(int(first) + int(second))
  elif op == "-":
    print(int(first) - int(second))
  elif op == "*":
   print(int(first) * int(second))
  else:
   print(int(first) / int(second))

"""."""